src/materials/urls.py
from django.conf.urls import url
from . import views
# from wkhtmltopdf.views import PDFTemplateView

app_name = 'materials'


urlpatterns = [
    # url(r'^$', views.HomeView.as_view(), name='home'),
    # url(r'^about/$', views.AboutView.as_view(), name='about'),
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^plot/$', views.plot, name='plot'),
    url(r'^search/$', views.search, name='search'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # url(r'^logout/$', views.logout_view, name='logout'),
]

src/z2/urls.py
import django
from django.conf.urls import include , url
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    # url(r'^login/$', auth_views.login, name='login'),
    url(r'^', include('materials.urls')),
    # url(r'^account/', include('accounts.urls')),
]
#urlpatterns += patterns('django.views.static',(r'^media/(?P<path>.*)','serve',{'document_root':settings.MEDIA_ROOT}), )
#urlpatterns += patterns('django.views.static',(r'^static/(?P<path>.*)','serve',{'document_root':settings.STATIC_ROOT}), )
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/materials/models.py
import datetime
from django.utils import timezone
from django.db import models


class Material(models.Model):
    formula    = models.CharField(max_length=200)
    elements   = models.CharField(max_length=200,default='')
    nel        = models.IntegerField(default=0)
    icsd       = models.IntegerField(default=0)
    source     = models.CharField(max_length=6,default='ICSD')
    spacegroup = models.CharField(max_length=20)
    spg        = models.IntegerField(default=0)
    pub_date   = models.DateTimeField('date published')
    nat        = models.IntegerField(default=0)
    ne         = models.IntegerField(default=0)
    zmax         = models.IntegerField(default=0)
    gap        = models.FloatField(default=0.0)
    dirgap     = models.FloatField(default=-1.0)
    metallicity = models.FloatField(default=-1.0)
#    volume = models.FloatField(default=0.0)
    matdir     = models.CharField(max_length=500,default='')
    centro     = models.BooleanField(default=False)
    nu         = models.CharField(max_length=7,default='?')
    dim        = models.IntegerField(default=0)
    bandsimage = models.ImageField(default='noimg.png')
    wccimage = models.ImageField(default='noimg.png')
    ciffile  = models.FileField(default='nocif.cif')
    scfin    = models.FileField(default='noscf.in')
    bandsin  = models.FileField(default='nobands.in')
    scfout   = models.FileField(default='noscf.out')
    bandsout = models.FileField(default='nobands.out')
    bandjson = models.FileField(default='nobands.json')
    isti     = models.BooleanField(default=False)
    isweyl   = models.BooleanField(default=False)
    isdirac  = models.BooleanField(default=False)
    selected = models.BooleanField(default=False)
    a        = models.FloatField(default=0.0)
    b        = models.FloatField(default=0.0)
    c        = models.FloatField(default=0.0)
    alpha    = models.FloatField(default=0.0)
    beta     = models.FloatField(default=0.0)
    gamma    = models.FloatField(default=0.0)
    lattice  = models.CharField(max_length=50,default='unknown')
    comment  = models.TextField(default='')
# for this should create a publication class
    publication = models.TextField(default='')

    def __str__(self):              # __unicode__ on Python 2
        return self.formula
    def has_bands(self):
       return self.bandsimage.name != 'noimg.png'
    def has_wcc(self):
        return self.wccimage.name != 'noimg.png'
    def has_cif(self):
        return self.wccimage.name != 'nocif.cif'
    def space_group_number(self):
        return int(self.spacegroup.split()[1].replace('(','').replace(')',''))

src/materials/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.views import generic
from django.core.paginator import Paginator,  EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required,user_passes_test
from django.utils.decorators import method_decorator
from django.db.models import Q
from django.conf import settings
from .models import Material
from django.db import models

DEFAULT_ORDERBY='formula'
DEFAULT_PAGINATE_BY=50
DEFAULT_PAGE=1
DEFAULT_ORDER='asc'
DEFAULT_MAX_LIST=['10','25','50','100']
FILTERS={'ltnel':'','gtnel':'','ltdgap':'','gtdgap':'',
         'centro':'','sel':'','nto':'','source':'all',
         'ltmet':'','gtmet':'','gtgap':0.0,'ltgap':'',
         'gtnat':'','ltnat':'','elements':'','nu':'',
         'topo':'all','icsd':'','spg':'','compo':'','dim':''}

FAMILIES={'TM3D':['Sc','Ti','V' ,'Cr','Mn','Fe','Co','Ni','Cu','Zn'],
'TM4D':['Y','Zr','Nb','Mo','Tc','Ru','Rh','Pd','Ag','Cd' ],
'TM5D':['La','Hf','Ta','W','Re','Os','Ir','Pt','Au','Hg' ],
'C1': ['Li','Na','K','Rb','Cs','XX','XX','XX','XX','XX' ],
'C2':['Be','Mg','Ca','Sr','Ba','XX','XX','XX','XX','XX'],
'C3':['Sc','Y','La' ,'XX','XX','XX','XX','XX','XX','XX'],
'C4':['Ti','Zr','Hf','XX','XX','XX','XX','XX','XX','XX'],
'C5':['V', 'Nb','Ta','XX','XX','XX','XX','XX','XX','XX'],
'C6':['Cr','Mo','W' ,'XX','XX','XX','XX','XX','XX','XX'],
'C7':['Mn','Tc','Re','XX','XX','XX','XX','XX','XX','XX'],
'C8':['Fe','Ru','Os','XX','XX','XX','XX','XX','XX','XX'],
'C9':['Co','Rh','Ir','XX','XX','XX','XX','XX','XX','XX'],
'C10':['Ni','Pd','Pt','XX','XX','XX','XX','XX','XX','XX'],
'C11':['Cu','Ag','Au','XX','XX','XX','XX','XX','XX','XX'],
'C12':['Zn','Cd','Hg','XX','XX','XX','XX','XX','XX','XX'],
'C13':['B','Al','Ga','In','Tl','XX','XX','XX','XX','XX'],
'C14':['C','Si','Ge','Sn','Pb','XX','XX','XX','XX','XX'],
'C15':['N','P' ,'As','Sb','Bi','XX','XX','XX','XX','XX'],
'C16':['O','S' ,'Se','Te','Po','XX','XX','XX','XX','XX'],
'C17':['F','Cl','Br','I','XX','XX','XX','XX','XX','XX'],
}


class HomeView(generic.TemplateView):
    template_name = 'materials/home_base.html'


class AboutView(generic.TemplateView):
    template_name = 'materials/about_base.html'


class IndexView(generic.ListView):
    model = Material
    # template_name = 'materials/index.html'
    template_name = 'materials/index_base.html'
    context_object_name = 'material_list'

    # @method_decorator(login_required)
    # def dispatch(self, *args, **kwargs):
    #     return super(IndexView, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        # pagination and ordering
        context['order'] = self.request.GET.get('order',DEFAULT_ORDER)
        context['orderby'] = self.request.GET.get('orderby',DEFAULT_ORDERBY)
        context['max'] = self.request.GET.get('max',DEFAULT_PAGINATE_BY)
        context['username'] = self.request.user.get_username()
        context['maxlist'] = DEFAULT_MAX_LIST
        context['plot'] = True
        page = self.request.GET.get('page',DEFAULT_PAGE)
        try:
           context['page']=int(page)
        except:
           context['page']=DEFAULT_PAGE
        # filters
        for k,v in FILTERS.items():
            context[k]=self.request.GET.get(k,'')
        return context

    def get_queryset(self):
#   get ordering and pagination
        orderby=self.request.GET.get('orderby',DEFAULT_ORDERBY)
#       check order can be used to order
        fields=[f.name for f in Material._meta.get_fields() ]
        if(orderby not in fields):
          orderby=DEFAULT_ORDERBY
        order=self.request.GET.get('order',DEFAULT_ORDER)
        ordering='-'+orderby if( order == 'desc' ) else orderby
#       filters
        filters={}
        for k,v in FILTERS.items():
            filters[k]=self.request.GET.get(k,'')
#       check filter type
        try:
          gtgap=float(filters['gtgap'])
        except:
          gtgap=FILTERS['gtgap']
        try:
          ltgap=float(filters['ltgap'])
        except:
          ltgap=FILTERS['ltgap']
        try:
          ltnat=int(filters['ltnat'])
        except:
          ltnat=FILTERS['ltnat']
        try:
          gtnat=int(filters['gtnat'])
        except:
          gtnat=FILTERS['gtnat']
        try:
          gtdgap=float(filters['gtdgap'])
        except:
          gtdgap=FILTERS['gtdgap']
        try:
          ltdgap=float(filters['ltdgap'])
        except:
          ltdgap=FILTERS['ltdgap']
        try:
          ltnel=int(filters['ltnel'])
        except:
          ltnel=FILTERS['ltnel']
        try:
          gtnel=int(filters['gtnel'])
        except:
          gtnel=FILTERS['gtnel']
        try:
          ltmet=float(filters['ltmet'])
        except:
          ltmet=FILTERS['ltmet']
        try:
          gtmet=float(filters['gtmet'])
        except:
          gtmet=FILTERS['gtmet']
        try:
          icsd=int(filters['icsd'])
        except:
          icsd=FILTERS['icsd']
        try:
          dim=int(filters['dim'])
        except:
          dim=FILTERS['dim']
        try:
          topo=filters['topo']
        except:
          topo=FILTERS['topo']
#       extract spg, formula and compositions list
        try:
          elist=[e.strip() for e in filters['elements'].split(',')]
        except:
          elist=[]
        try:
          clist=[c.strip() for c in filters['compo'].split(',')]
        except:
          clist=[]
        try:
          spg=filters['spg'].split(',')
          spglist=[]
          for x in spg:
             if('-' in x ):
                   xl=x.split('-')
                   for i in range(int(xl[0]),int(xl[1])+1):
                      spglist.append(i)
             else:
                   spglist.append(int(x))
        except:
          spglist=[]

####### Filter  #######################
        q=Material.objects.order_by(ordering)
        if( gtgap != ''): q=q.filter( gap__gte = gtgap)
        if( ltgap != ''): q=q.filter( gap__lte = ltgap)
        if( gtdgap != ''): q=q.filter( dirgap__gte = gtdgap)
        if( ltdgap != ''): q=q.filter( dirgap__lte = ltdgap)
        if( gtmet != ''): q=q.filter( metallicity__gte = gtmet)
        if( ltmet != ''): q=q.filter( metallicity__lte = ltmet)
        if( gtnat != ''): q=q.filter( nat__gte = gtnat)
        if( ltnat != ''): q=q.filter( nat__lte = ltnat)
        if( gtnel != ''): q=q.filter( nel__gte = gtnel)
        if( ltnel != ''): q=q.filter( nel__lte = ltnel)
        if( icsd != ''): q=q.filter( icsd = icsd )
        if( filters['source'] == 'COD'): q=q.filter( Q(source  = 'COD') | Q(source = 'OCD') )  # because of stupid type in the database -- should be corrected
        if( filters['source'] == 'ICSD'): q=q.filter( source = filters['source'] )
        if( spglist != []): q=q.filter( spg__in = spglist )
        if( filters['nu'] != ''): q=q.filter( nu = filters['nu'] )
        if( topo=='ti'): q=q.filter( isti = True )
        if( topo=='dirac'): q=q.filter( isdirac = True )
        if( topo=='weyl'): q=q.filter( isweyl = True )
        if( topo=='undef'):
             q=q.filter( isweyl = False )
             q=q.filter( isdirac = False )
             q=q.filter( isti = False )
        if( filters['nto'] == 't'):
          q=q.exclude( nu = '(0;000)')
          q=q.exclude( nu = '?')
        if( dim == 1 or dim == 2 or dim == 3): q=q.filter( dim = dim )
        if( filters['sel'] == 't'): q=q.filter( selected = True )
        if( filters['centro'] == 'c'): q=q.filter( centro = True )
        if( filters['centro'] == 'n'): q=q.filter( centro = False )
        for e in elist:
         if(e != ''):
          if(e.startswith('-')):
           q=q.exclude( formula__contains = e.replace('-','') )
          else:
           q=q.filter( formula__contains = e )
        for c in clist:
         if(c != ''):
          if(c.startswith('-')):
           x=c.replace('-','')
           if x in FAMILIES.keys():
             q=q.exclude(Q(elements__contains='-'+FAMILIES[x][0]+'-') |
                        Q(elements__contains='-'+FAMILIES[x][1]+'-') |
                        Q(elements__contains='-'+FAMILIES[x][2]+'-') |
                        Q(elements__contains='-'+FAMILIES[x][3]+'-') |
                        Q(elements__contains='-'+FAMILIES[x][4]+'-') |
                        Q(elements__contains='-'+FAMILIES[x][5]+'-') |
                        Q(elements__contains='-'+FAMILIES[x][6]+'-') |
                        Q(elements__contains='-'+FAMILIES[x][7]+'-') |
                        Q(elements__contains='-'+FAMILIES[x][8]+'-') |
                        Q(elements__contains='-'+FAMILIES[x][9]+'-')
                       )
           else:
             q=q.exclude(elements__contains=c+'-')

          else:
           if c in FAMILIES.keys():
             q=q.filter(Q(elements__contains='-'+FAMILIES[c][0]+'-') |
                        Q(elements__contains='-'+FAMILIES[c][1]+'-') |
                        Q(elements__contains='-'+FAMILIES[c][2]+'-') |
                        Q(elements__contains='-'+FAMILIES[c][3]+'-') |
                        Q(elements__contains='-'+FAMILIES[c][4]+'-') |
                        Q(elements__contains='-'+FAMILIES[c][5]+'-') |
                        Q(elements__contains='-'+FAMILIES[c][6]+'-') |
                        Q(elements__contains='-'+FAMILIES[c][7]+'-') |
                        Q(elements__contains='-'+FAMILIES[c][8]+'-') |
                        Q(elements__contains='-'+FAMILIES[c][9]+'-')
                       )
           else:
             q=q.filter(elements__contains='-'+c+'-')
########################################################################
#       pagination
        paginate_by=DEFAULT_PAGINATE_BY
        paginate_by=self.request.GET.get('max',DEFAULT_PAGINATE_BY)
        try:
          paginate_by=int(paginate_by)
        except:

src/materials/templates/materials/base.html
{% load static %}
<html>
    <head>
         <meta charset="UTF-8">
         <meta name="author" content="Gabriel Autes">
	 <title>{% block headtitle %}TopoMat Database{% endblock %} </title>
<!-- Favicon -->
         <link rel="apple-touch-icon" sizes="57x57" href="{% static 'img/apple-icon-57x57.png' %}">
         <link rel="apple-touch-icon" sizes="60x60" href="{% static 'img/apple-icon-60x60.png' %}">
         <link rel="apple-touch-icon" sizes="72x72" href="{% static 'img/apple-icon-72x72.png' %}">
         <link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/apple-icon-76x76.png' %}">
         <link rel="apple-touch-icon" sizes="114x114" href="{% static 'img/apple-icon-114x114.png' %}">
         <link rel="apple-touch-icon" sizes="120x120" href="{% static 'img/apple-icon-120x120.png' %}">
         <link rel="apple-touch-icon" sizes="144x144" href="{% static 'img/apple-icon-144x144.png' %}">
         <link rel="apple-touch-icon" sizes="152x152" href="{% static 'img/apple-icon-152x152.png' %}">
         <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/apple-icon-180x180.png' %}">
         <link rel="icon" type="image/png" sizes="192x192"  href="{% static 'img/android-icon-192x192.png' %}">
         <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon-32x32.png' %}">
         <link rel="icon" type="image/png" sizes="96x96" href="{% static 'img/favicon-96x96.png' %}">
         <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon-16x16.png' %}">
         <link rel="manifest" href="{% static 'img/manifest.json' %}">
         <meta name="msapplication-TileColor" content="#ffffff">
         <meta name="msapplication-TileImage" content="{% static 'img/ms-icon-144x144.png' %}">
         <meta name="theme-color" content="#ffffff">
<!-- Bootstrap -->
         <!-- Material Design fonts -->
	 <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" type="text/css">
	 <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<link href="{% static 'css/custom.css'%}" rel="stylesheet">
	<!-- jQuery library -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <!-- Latest compiled JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <meta name="viewport" content="width=device-width, initial-scale=1">
	
    <script src="{% static 'js/iframeResizer.contentWindow.min.js' %}"></script> 

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-125400393-1"></script>
    <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

        gtag('config', 'UA-125400393-1');
    </script>


    </head>
    <body>
<!-- Title bar -->
        <div class="container-fluid default-primary-color card-2" >
		<h1>{% block title %}TopoMat Database <small>beta</small>{% endblock %}</h1>
        </div>
<!-- Nav. bar -->
	{% block navbar %}
	<nav class="navbar navbar-inverse navbar-static-top  .navbar {margin-bottom: 0;}">
                {% url 'materials:index' as index_url %}
		<div class="container-fluid card-2">
			<ul class="nav navbar-nav">
				<li {% if request.get_full_path == index_url  %} class='active' {% endif %}>
					<a href="{{index_url}}"> <span class="glyphicon glyphicon-list"></span>&nbsp; Database </a>
				</li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				{% if plot %}
				<li>
					<form class="navbar-form inline" id="plotform" action="{% url 'materials:plot' %}" method="get" accept-charset="utf-8">
						<select class="form-control" name="x">
							<option value="nat">X-axis</option>
							<option value="nat">nat</option>
							<option value="ne">ne</option>
							<option value="nel">nelement</option>
							<option value="dim">dim</option>
							<option value="gap">gap</option>
							<option value="dirgap">dir. gap</option>
							<option value="metallicity">met</option>
							<option value="zmax">zmax</option>
							<option value="volume">volume</option>
							<!-- <option value="nu">nu</option> -->
						</select>
						<select class="form-control" name="y">
							<option value="gap">Y-axis</option>
							<option value="nat">nat</option>
							<option value="ne">ne</option>
							<option value="nel">nelement</option>
							<option value="dim">dim</option>
							<option value="gap">gap</option>
							<option value="dirgap">dir. gap</option>
							<option value="metallicity">met</option>
							<option value="zmax">zmax</option>
							<option value="volume">volume</option>
						</select>
						<button type="submit" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
							<span class="glyphicon glyphicon-stats" aria-hidden="true"></span> Plot
						</button>
					</form>
				</li>
				{% endif%}
				{% if from_list %} 
				<li><a href='{{ source_url }}' > <span class="glyphicon glyphicon-arrow-left"></span> Back to list </a> </li>
				{% endif %} 
				<li>
					<form class="navbar-form inline" id="searchform" action="{% url 'materials:search' %}" method="get" accept-charset="utf-8" role="search">
						<div class="form-group" style="display:inline;">
							<div class="input-group" style="display:table;">
								<input class="form-control" name="search" placeholder="Quick search"  autofocus="autofocus" type="text">
								<span class="input-group-addon"><span class="glyphicon glyphicon-search"></span></span>
							</div>
						</div>

					</form>
			
				</li>
			</ul>
		</div>
	</nav>
       {% endblock %}
       {% block content %}
       {% endblock %}
       {% if plot %}
	<div class="modal fade" id="myModal" role="dialog">
	<div class="modal-dialog modal-sm">
		<div class="modal-content">
			<div class="modal-body ">
				<div class="text-center"><h4 >Plotting...</h4> </div>
				<img id='wheel' class='img-responsive center-block'  src='{% static 'img/puff.svg' %}' width=40% />
				<br>
			</div>
		</div>
	</div>
	</div>
       {% endif%}
<!-- Scripts -->
	{% block script %}
        {% endblock %}
 <div style ="position: relative" data-iframe-height></div>
    </body>
</html>

src/materials/templates/materials/plot_base.html
{% extends 'materials/base.html' %}
{% load materials_extra %}
{% load static %}
{% block script %}
         <script type="text/javascript" src="{% static 'js/chartjs/Chart.js' %}"></script>
	 <script type="text/javascript" src="{% static 'js/chartjs/Chart.kscale.js' %}"></script>
	 <script type="text/javascript" src="{% static 'js/chartjs/chartjs-plugin-zoom.js' %}"></script>
{% endblock %}
{% block content %}
<body>
{% if pk_list %}
<!-- content -->
  <div class="container default-background card-2" >
</br>


   <canvas id="myChart" width="800" height="500" >
 </canvas>
 <noscript><div class='panel' > <div class="panel-body text-center block-center "><p class='bg-danger'>You must have javascript enabled to display the plot</p></div></div></noscript>

<script>
window.onload = function() {
	var ctx = document.getElementById("myChart").getContext('2d');
	var data = { datasets: {{data| safe}}};
	var myChart = new Chart(ctx, {
		type: 'scatter',
		data: data, 
		options: {
	    tooltips: { mode: 'nearest',
	       callbacks: { label: function(tooltipItem, myChart){
                              return data.datasets[tooltipItem.datasetIndex].label  ; 
                            } } },
	    legend: { display: false, },
	    zoom: { enabled : true, mode: 'xy'  },
	    pan: { enabled : true, mode: 'xy'  },
	    scales: {
		    yAxes: [{
			    scaleLabel: {
				    display: true,
				    labelString: '{{y}}'
			    }
		    }],
		    xAxes: [{
			    scaleLabel: {
				    display: true,
				    labelString: '{{x}}'
			    }
		    }]
  }
    } 
 
 });

var canvas = document.getElementById("myChart");
canvas.onclick = function(evt){
    var activePoints = myChart.getElementAtEvent(evt);
	if(typeof activePoints[0] != 'undefined'){ 
		var indx = activePoints[0]._datasetIndex; 
		var pk=data.datasets[indx].pk;
		var url="{% url 'materials:index' %}/"+String(pk);
		location.href=url;
	}
};


canvas.onmousemove = function(evt){
    var activePoints = myChart.getElementAtEvent(evt);
	if(typeof activePoints[0] != 'undefined'){ this.style.cursor='pointer';}
	else {this.style.cursor='default';}
};


resetZoom = function() {
	myChart.resetZoom()
}

};


</script>
<div class='form-group'>
<button  class="btn btn-primary" onclick="resetZoom()" ><span class="glyphicon glyphicon-refresh" aria-hidden="true"></span> Reset zoom</button>
</div>

{% endif %}

  </div>
  {% endblock %}